---
- name: Step 0 - Fetch and Extract Roles from S3
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure base directory exists
      become: yes
      file:
        path: /etc/ansible
        state: directory
        mode: '0755'

    - name: Download mc and fetch roles from S3
      shell: |
        if [ ! -f "./mc" ]; then
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
        fi
        chmod +x ./mc
        ./mc alias set mys3 http://213.155.21.230:9000 {{ s3_user }} {{ s3_password }}
        ./mc cp mys3/ansible-storage/roles_from_s3.tar.gz /tmp/roles.tar.gz
      args:
        chdir: "{{ ansible_env.PWD }}"
        executable: /bin/bash

    - name: Clean old roles before extraction
      become: yes
      file:
        path: /etc/ansible/roles
        state: absent

    - name: Unpack roles to /etc/ansible/
      become: yes
      unarchive:
        src: /tmp/roles.tar.gz
        dest: /etc/ansible/
        remote_src: yes

- name: Step 1 - Configure Apache Servers
  hosts: webservers
  become: yes
  tasks:
    - name: Execute apache role
      include_role:
        name: apache

- name: Step 2 - Configure Load Balancer
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Execute haproxy role
      include_role:
        name: haproxy
