---
- name: Prepare Ansible Roles from S3
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure roles directory exists
      become: yes
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'

    - name: Download roles archive from MinIO
      shell: "/home/centos/mc cp mys3/ansible-storage/roles_from_s3.tar.gz /tmp/roles.tar"
      register: download_result

    - name: Extract roles to Ansible folder
      become: yes
      unarchive:
        src: /tmp/roles.tar
        dest: /etc/ansible/roles/
        remote_src: yes
      when: download_result.rc == 0

- name: Настройка Apache на веб-серверах
  hosts: webservers
  become: yes
  roles:
    - apache

- name: Настройка балансировщика HAProxy
  hosts: loadbalancer
  become: yes
  roles:
    - haproxy
